
// This actionType is used to store constants
export const ADD_INGREDIENT='ADD_INGREDIENT';
export const DELETE_INGREDIENT='DELETE_INGREDIENT';
export const RESET_INGREDIENT='RESET_INGREDIENT';
export const BURGER_PURCHASE_SUCCESSFULL='BURGER_PURCHASE_SUCCESSFULL'
export const BURGER_PURCHASE_FAIL='BURGER_PURCHASE_FAIL'


export const FETCH_ORDER_START='FETCH_ORDER_START'
export const FETCH_ORDER_SUCCESSFULL='FETCH_ORDER_SUCCESSFULL'
export const FETCH_ORDER_FAIL='FETCH_ORDER_FAIL'
export const FETCH_ORDER='FETCH_ORDER'
